# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLq5mpeMIoK0lK8h3x4PEfqnDqyy13y5
"""

import streamlit as st

# Streamlit app
st.title("Social Media Sentiment Analyzer")
keyword = st.text_input("Enter a keyword to analyze:")
if st.button("Analyze"):
    tweets_df = fetch_tweets(keyword, count=50)
    tweets_df = analyze_sentiments(tweets_df)
    st.write("Sentiment Results:")
    st.dataframe(tweets_df)
    st.write("Visualization:")
    sentiment_counts = tweets_df["sentiment"].value_counts()
    st.bar_chart(sentiment_counts)
